export enum AppErrorCodes {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL = 'INTERNAL',

  UNKNOWN_USER = 'UNKNOWN_USER',
  UNKNOWN_AGENT = 'UNKNOWN_AGENT',
  UNKNOWN_TEAM = 'UNKNOWN_TEAM',
  UNKNOWN_CHAT = 'UNKNOWN_CHAT',
  UNKNOWN_CHAT_MESSAGE = 'UNKNOWN_CHAT_MESSAGE',
  UNKNOWN_CHAT_TAG = 'UNKNOWN_CHAT_TAG',

  CHAT_IS_CLOSED = 'CHAT_IS_CLOSED',
  MISSING_ACCESS_ERROR = 'MISSING_ACCESS_ERROR'
}
