export enum AppErrorCodes {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL = 'INTERNAL'
}
