export enum ViolationReasons {
  REQUIRED = 'REQUIRED',
  BAD_LENGTH = 'BAD_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  MIN_LENGTH = 'MIN_LENGTH',
  CHOICES = 'CHOICES',

  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  NAME_ALREADY_REGISTERED = 'NAME_ALREADY_REGISTERED',
}
