version: '3.9'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=howder
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  lint:
    build: .
    entrypoint: yarn lint
    environment:
      - NODE_ENV=test
    volumes:
      - .:/howder
      - /howder/node_modules

  test:
    build: .
    entrypoint: yarn test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/howder
      - /howder/node_modules
    depends_on:
      database:
        condition: service_healthy

  migrate:
    build: .
    entrypoint: yarn migrate
    environment:
      - NODE_ENV=development
    volumes:
      - .:/howder
      - /howder/node_modules
    depends_on:
      database:
        condition: service_healthy

  howder-server:
    build: .
    entrypoint: yarn dev
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/howder
      - /howder/node_modules
    depends_on:
      - database
      - migrate