version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: database_container
    environment:
      - POSTGRES_DB=support-chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432