version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: database_container
    environment:
      - POSTGRES_DB=howder
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=development
    networks:
      - howder_network
    ports:
      - 5432:5432

networks:
  chatter_network:
    driver: bridge
    name: howder_network