version: '3.9'

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=howder
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_server:
    build: .
    entrypoint: /howder/scripts/entrypoint_dev.sh
    environment:
      - NODE_ENV=development
    ports:
      - 3333:3333
    volumes:
      - .:/howder
    depends_on:
      - database
