export const ErrorCodes = {
  REQUIRED: 'REQUIRED',
  BAD_LENGTH: 'BAD_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  MIN_LENGTH: 'MIN_LENGTH',

  INVALID_EMAIL: 'INVALID_EMAIL',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_REGISTERED: 'USERNAME_ALREADY_REGISTERED'
}
