export enum AppErrorCodes {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL = 'INTERNAL',

  UNKNOWN_AGENT = 'UNKNOWN_AGENT',
  UNKNOWN_WORKSPACE = 'UNKNOWN_WORKSPACE',
  UNKNOWN_MEMBER = 'UNKNOWN_MEMBER',
  UNKNOWN_USER = 'UNKNOWN_USER',
  UNKNOWN_TEAM = 'UNKNOWN_TEAM',
  UNKNOWN_CHAT = 'UNKNOWN_CHAT',
  UNKNOWN_MESSAGE = 'UNKNOWN_CHAT_MESSAGE',
  UNKNOWN_TAG = 'UNKNOWN_TAG',

  CHAT_ALREADY_OPEN = 'CHAT_ALREADY_OPEN',
  CHAT_ALREADY_CLOSED = 'CHAT_ALREADY_CLOSED',
  CHAT_ALREADY_HAS_MEMBER_ASSIGNED = 'CHAT_ALREADY_HAS_MEMBER_ASSIGNED',
  CHAT_HAS_NO_MEMBER_ASSIGNED = 'CHAT_HAS_NO_MEMBER_ASSIGNED'
}
